# Generated by Django 5.2.7 on 2026-06-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=50)),
                ('video_filename', models.CharField(max_length=255)),
                ('video_path', models.CharField(max_length=500)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'face_recordings',
            },
        ),
    ]
