# Generated by Django 5.2.7 on 2026-06-08 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facerecording',
            name='status',
        ),
    ]
