# Generated by Django 5.2.7 on 2026-06-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_app', '0002_remove_facerecording_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facerecording',
            name='emp_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
