# Generated by Django 5.2.7 on 2026-06-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_app', '0003_alter_facerecording_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='facerecording',
            name='employee_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
