# Generated by Django 5.2.7 on 2026-06-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_app', '0004_facerecording_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='facerecording',
            name='department',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
