# Generated by Django 5.2.10 on 2026-02-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_recognizedface_phone_mail_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognizedface',
            name='activity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recognizedface',
            name='bbox',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recognizedface',
            name='helmet_detected',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_type',
            field=models.CharField(choices=[('meeting', 'Meeting Rule'), ('allowed_place', 'Allowed Place'), ('restricted_zone', 'Restricted Zone'), ('in_out', 'In / Out Time Rule'), ('group', 'Group Gathering'), ('phone', 'Phone Usage'), ('helmet', 'Helmet Safety Rule')], max_length=30),
        ),
    ]
