# Generated by Django 5.2.10 on 2026-03-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_emailsend'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsend',
            name='unauthorized_person',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
