# Generated by Django 5.2.7 on 2026-04-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_emailsend_unauthorized_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='rule_type',
            field=models.CharField(choices=[('meeting', 'Meeting Rule'), ('allowed_place', 'Allowed Place'), ('restricted_zone', 'Restricted Zone'), ('in_out', 'In / Out Time Rule'), ('group', 'Group Gathering'), ('phone', 'Phone Usage'), ('helmet', 'Helmet Safety Rule'), ('count', 'Count Rule')], max_length=30),
        ),
    ]
