# Generated by Django 5.2.7 on 2026-06-05 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_emailsend_unauthorized_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recognizedface',
            name='activity',
        ),
    ]
