# Generated by Django 5.2.7 on 2026-06-08 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_remove_recognizedface_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaceRecording',
        ),
    ]
