# Generated by Django 5.2.7 on 2026-04-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_alter_rule_rule_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsend',
            name='close_count',
        ),
        migrations.RemoveField(
            model_name='emailsend',
            name='known_employee',
        ),
        migrations.RemoveField(
            model_name='emailsend',
            name='unknown_visitor',
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_type',
            field=models.CharField(choices=[('meeting', 'Meeting Rule'), ('allowed_place', 'Allowed Place'), ('restricted_zone', 'Restricted Zone'), ('in_out', 'In / Out Time Rule'), ('phone', 'Phone Usage'), ('helmet', 'Helmet Safety Rule'), ('no_employee', 'No Employee Rule')], max_length=30),
        ),
    ]
