# Generated by Django 5.2.7 on 2026-04-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_remove_emailsend_close_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='rule_type',
            field=models.CharField(choices=[('meeting', 'Meeting Rule'), ('allowed_place', 'Allowed Place'), ('restricted_zone', 'Restricted Zone'), ('in_out', 'In / Out Time Rule'), ('phone', 'Phone Usage'), ('helmet', 'Helmet Safety Rule'), ('no_employee', 'No Employee Rule'), ('group', 'Group Detection Rule')], max_length=30),
        ),
    ]
