# Generated by Django 5.2.7 on 2026-05-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_alter_rule_rule_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name', models.CharField(max_length=100)),
                ('boundary_name', models.CharField(max_length=100)),
                ('points', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'camera_boundary',
                'ordering': ['camera_name', 'boundary_name'],
                'unique_together': {('camera_name', 'boundary_name')},
            },
        ),
    ]
