# Generated by Django 5.2.7 on 2026-05-25 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_cameraboundary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recognizedface',
            name='activity',
        ),
    ]
