# Generated by Django 5.2.7 on 2026-05-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_remove_recognizedface_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoEmployeeShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'db_table': 'no_emp_shift',
            },
        ),
        migrations.AddField(
            model_name='emailsend',
            name='shift_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
