# Generated by Django 5.2.7 on 2026-05-30 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_noemployeeshift_emailsend_shift_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoEmployeeShift',
        ),
        migrations.RemoveField(
            model_name='emailsend',
            name='shift_name',
        ),
    ]
