# Generated by Django 5.2.7 on 2026-06-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_noemployeeshift_emailsend_shift_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noemployeeshift',
            name='end_time',
            field=models.TimeField(verbose_name=0),
        ),
        migrations.AlterField(
            model_name='noemployeeshift',
            name='start_time',
            field=models.TimeField(verbose_name=0),
        ),
    ]
