# Generated by Django 5.2.7 on 2026-06-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_alter_noemployeeshift_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noemployeeshift',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='noemployeeshift',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
